"""WorldForge · 封闭决策动力学模拟器

Base classes for world state and environment.

Core idea:
  state(t+1) = f(state(t), action)
  
  where action comes from the agent (LingYao Decision Engine),
  and f() is defined by each environment's transition rules.
"""
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Any, Callable
import json, random, copy
from abc import ABC, abstractmethod


@dataclass
class WorldState:
    """Base class for all environment states."""
    episode: int = 0
    step: int = 0
    done: bool = False

    def to_dict(self) -> Dict:
        return asdict(self)

    def clone(self) -> "WorldState":
        return copy.deepcopy(self)

    def summary(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)


@dataclass
class Action:
    """An action taken by the agent."""
    type: str        # e.g., "empathize", "guide", "execute", "inform"
    params: Dict = field(default_factory=dict)
    raw_text: str = ""  # The actual response generated by LLM

    def to_dict(self) -> Dict:
        return {"type": self.type, "params": self.params}


@dataclass
class StepResult:
    """Result of one step in the environment."""
    state: WorldState
    action: Action
    reward: float
    done: bool
    info: Dict = field(default_factory=dict)


class Environment(ABC):
    """Base class for a closed-world simulation environment."""

    def __init__(self, name: str, config: Optional[Dict] = None):
        self.name = name
        self.config = config or {}
        self.history: List[StepResult] = []

    @abstractmethod
    def reset(self) -> WorldState:
        """Reset environment, return initial state."""
        pass

    @abstractmethod
    def step(self, action: Action) -> StepResult:
        """Apply action, transition state, return result."""
        pass

    @abstractmethod
    def available_actions(self, state: WorldState) -> List[str]:
        """Return list of valid action types for current state."""
        pass

    def render(self, state: WorldState) -> str:
        """Return a human-readable string of current state."""
        return state.summary()

    def get_metrics(self) -> Dict:
        """Aggregate metrics across all steps."""
        if not self.history:
            return {}
        rewards = [r.reward for r in self.history]
        return {
            "total_reward": sum(rewards),
            "avg_reward": sum(rewards) / len(rewards),
            "steps": len(self.history),
            "final_state": self.history[-1].state.to_dict() if self.history else None
        }


def build_state_text(state: WorldState) -> str:
    """Convert state to a prompt-friendly text for LingYao/LLM."""
    d = state.to_dict()
    parts = []
    for k, v in d.items():
        if k in ("episode", "step", "done"):
            continue
        parts.append(f"{k}: {v}")
    return ", ".join(parts)
